### ISSUE TITLE
`block_groups` function does not exist

### ISSUE THREAD

**Issue by anastasia** [ericrobskyhuntley/deduplicate-owners#13]
Has it been accidentally removed?
https://github.com/ericrobskyhuntley/deduplicate-owners/blob/261d39b4f72c9ae87d23a7b7474812d24a215bc5/deduplicate-owners.R#L601

**Comment by ericrobskyhuntley** [comment]
Ah - thanks. Only sort of. I cut the function that was loading `tigris` previously, which is the library that includes `block_groups()` (hello silly, silly function design). Fixed in d2e7e6b
